### ISSUE TITLE
회의때 나온 변경사항 반영하기

### ISSUE THREAD

**Issue by Flre-fly** [TWOGATH3R/twogather-web-backend#42]
## Description
- 배포하면서 오류가 생겼거나 프론트와 설정이 맞지 않은 부분에 대해서 변경한다
## To-Do List
- [x] email 중복허용안함 처리
- [x] refresh-token 헤더의 "-" 특수문자 제거
- [x] cors - 프론트 배포주소에 한에서 해제
