### ISSUE TITLE
api docs 리팩토링

### ISSUE THREAD

**Issue by Flre-fly** [TWOGATH3R/twogather-web-backend#70]
## Description
- api 문서 리팩토링
## To-Do List
- [x] deletelike storeid에 대한 설명 변경
- [x] businesshour save시 저장된 일주일 정보로 응답해야한다
- [x] businesshour update시 update한 정보로 응답해야한다
- [x] 권한이 필요한 경우 명시해준다
- [x] error에 대한 명세 추가하기

## Etc
#11
